/**
 * Official IMD (WMO Synoptic Standard) Weather Codes Mapping (00 - 99)
 * Used across IMD Current Weather (current_wx), AWS/ARG telemetry, and synoptic observations.
 */

export interface IMDWeatherCodeInfo {
  code: number;
  label: string;
  category: 'CLEAR' | 'CLOUDY' | 'FOG' | 'DRIZZLE' | 'RAIN' | 'SNOW' | 'THUNDERSTORM' | 'DUST' | 'HAIL' | 'SQUALL';
  description: string;
  iconName: string;
}

export const IMD_WEATHER_CODES: Record<number, IMDWeatherCodeInfo> = {
  0: { code: 0, label: 'Cloud development not observed or not observable', category: 'CLEAR', description: 'Clear sky or slight cloud', iconName: 'Sun' },
  1: { code: 1, label: 'Clouds generally dissolving or becoming less developed', category: 'CLEAR', description: 'Mainly clear, clouds dissipating', iconName: 'Sun' },
  2: { code: 2, label: 'State of sky on the whole unchanged', category: 'CLOUDY', description: 'Partly cloudy', iconName: 'CloudSun' },
  3: { code: 3, label: 'Clouds generally forming or developing', category: 'CLOUDY', description: 'Clouds increasing', iconName: 'Cloud' },
  4: { code: 4, label: 'Visibility reduced by smoke', category: 'FOG', description: 'Haze / Smoke', iconName: 'Haze' },
  5: { code: 5, label: 'Haze', category: 'FOG', description: 'Hazy conditions', iconName: 'Haze' },
  6: { code: 6, label: 'Widespread dust in suspension in the air', category: 'DUST', description: 'Dust in suspension', iconName: 'Wind' },
  7: { code: 7, label: 'Dust or sand raised by wind', category: 'DUST', description: 'Blowing dust or sand', iconName: 'Wind' },
  8: { code: 8, label: 'Well-developed dust whirl(s) or sand whirl(s)', category: 'DUST', description: 'Dust whirls', iconName: 'Wind' },
  9: { code: 9, label: 'Duststorm or sandstorm within sight', category: 'DUST', description: 'Duststorm in vicinity', iconName: 'Wind' },
  10: { code: 10, label: 'Mist', category: 'FOG', description: 'Mist / Shallow moisture', iconName: 'CloudFog' },
  11: { code: 11, label: 'Patches of shallow fog or ice fog', category: 'FOG', description: 'Shallow fog patches', iconName: 'CloudFog' },
  12: { code: 12, label: 'More or less continuous shallow fog', category: 'FOG', description: 'Continuous shallow fog', iconName: 'CloudFog' },
  13: { code: 13, label: 'Lightning visible, no thunder heard', category: 'THUNDERSTORM', description: 'Distant lightning', iconName: 'Zap' },
  14: { code: 14, label: 'Precipitation within sight, not reaching the ground', category: 'CLOUDY', description: 'Virga', iconName: 'CloudDrizzle' },
  15: { code: 15, label: 'Precipitation within sight, reaching ground at distance', category: 'RAIN', description: 'Distant precipitation', iconName: 'CloudRain' },
  16: { code: 16, label: 'Precipitation within sight, near to but not at station', category: 'RAIN', description: 'Nearby precipitation', iconName: 'CloudRain' },
  17: { code: 17, label: 'Thunderstorm, but no precipitation at time of observation', category: 'THUNDERSTORM', description: 'Thunderstorm without rain', iconName: 'Zap' },
  18: { code: 18, label: 'Squalls at or within sight of station', category: 'SQUALL', description: 'Squally winds', iconName: 'Wind' },
  19: { code: 19, label: 'Funnel cloud(s) (tornado or waterspout)', category: 'SQUALL', description: 'Funnel cloud / Waterspout', iconName: 'Tornado' },
  20: { code: 20, label: 'Drizzle or snow grains not falling as shower', category: 'DRIZZLE', description: 'Drizzle earlier', iconName: 'CloudDrizzle' },
  21: { code: 21, label: 'Rain (not falling as shower)', category: 'RAIN', description: 'Continuous rain earlier', iconName: 'CloudRain' },
  22: { code: 22, label: 'Snow (not falling as shower)', category: 'SNOW', description: 'Snow earlier', iconName: 'Snowflake' },
  23: { code: 23, label: 'Rain and snow or ice pellets', category: 'SNOW', description: 'Mixed rain and snow earlier', iconName: 'CloudSnow' },
  24: { code: 24, label: 'Freezing drizzle or freezing rain', category: 'RAIN', description: 'Freezing precipitation earlier', iconName: 'CloudRain' },
  25: { code: 25, label: 'Shower(s) of rain', category: 'RAIN', description: 'Rain showers earlier', iconName: 'CloudRain' },
  26: { code: 26, label: 'Shower(s) of snow, or of rain and snow', category: 'SNOW', description: 'Snow showers earlier', iconName: 'CloudSnow' },
  27: { code: 27, label: 'Shower(s) of hail, or of rain and hail', category: 'HAIL', description: 'Hail showers earlier', iconName: 'CloudHail' },
  28: { code: 28, label: 'Fog or ice fog', category: 'FOG', description: 'Fog in past hour', iconName: 'CloudFog' },
  29: { code: 29, label: 'Thunderstorm (with or without precipitation)', category: 'THUNDERSTORM', description: 'Thunderstorm in past hour', iconName: 'Zap' },
  30: { code: 30, label: 'Slight or moderate duststorm/sandstorm, decreasing', category: 'DUST', description: 'Duststorm decreasing', iconName: 'Wind' },
  31: { code: 31, label: 'Slight or moderate duststorm/sandstorm, no change', category: 'DUST', description: 'Duststorm steady', iconName: 'Wind' },
  32: { code: 32, label: 'Slight or moderate duststorm/sandstorm, increasing', category: 'DUST', description: 'Duststorm increasing', iconName: 'Wind' },
  33: { code: 33, label: 'Severe duststorm or sandstorm, decreasing', category: 'DUST', description: 'Severe duststorm decreasing', iconName: 'Wind' },
  34: { code: 34, label: 'Severe duststorm or sandstorm, no change', category: 'DUST', description: 'Severe duststorm steady', iconName: 'Wind' },
  35: { code: 35, label: 'Severe duststorm or sandstorm, increasing', category: 'DUST', description: 'Severe duststorm increasing', iconName: 'Wind' },
  36: { code: 36, label: 'Slight or moderate drifting snow', category: 'SNOW', description: 'Drifting snow (low)', iconName: 'Snowflake' },
  37: { code: 37, label: 'Heavy drifting snow', category: 'SNOW', description: 'Heavy drifting snow', iconName: 'Snowflake' },
  38: { code: 38, label: 'Slight or moderate blowing snow', category: 'SNOW', description: 'Blowing snow (high)', iconName: 'Snowflake' },
  39: { code: 39, label: 'Heavy blowing snow', category: 'SNOW', description: 'Heavy blowing snow', iconName: 'Snowflake' },
  40: { code: 40, label: 'Fog or ice fog at a distance', category: 'FOG', description: 'Distant fog', iconName: 'CloudFog' },
  41: { code: 41, label: 'Fog or ice fog in patches', category: 'FOG', description: 'Fog in patches', iconName: 'CloudFog' },
  42: { code: 42, label: 'Fog/ice fog, sky visible, becoming thinner', category: 'FOG', description: 'Thinning fog, sky visible', iconName: 'CloudFog' },
  43: { code: 43, label: 'Fog/ice fog, sky invisible, becoming thinner', category: 'FOG', description: 'Thinning dense fog', iconName: 'CloudFog' },
  44: { code: 44, label: 'Fog/ice fog, sky visible, no change', category: 'FOG', description: 'Fog, sky visible', iconName: 'CloudFog' },
  45: { code: 45, label: 'Fog or ice fog, sky invisible, no change', category: 'FOG', description: 'Dense fog, sky obscured', iconName: 'CloudFog' },
  46: { code: 46, label: 'Fog/ice fog, sky visible, becoming thicker', category: 'FOG', description: 'Thickening fog, sky visible', iconName: 'CloudFog' },
  47: { code: 47, label: 'Fog or ice fog, sky invisible, becoming thicker', category: 'FOG', description: 'Dense thickening fog', iconName: 'CloudFog' },
  48: { code: 48, label: 'Fog, depositing rime, sky visible', category: 'FOG', description: 'Freezing fog, sky visible', iconName: 'CloudFog' },
  49: { code: 49, label: 'Fog, depositing rime, sky invisible', category: 'FOG', description: 'Freezing fog, sky invisible', iconName: 'CloudFog' },
  50: { code: 50, label: 'Drizzle, not freezing, intermittent, slight', category: 'DRIZZLE', description: 'Intermittent slight drizzle', iconName: 'CloudDrizzle' },
  51: { code: 51, label: 'Drizzle, not freezing, continuous, slight', category: 'DRIZZLE', description: 'Continuous slight drizzle', iconName: 'CloudDrizzle' },
  52: { code: 52, label: 'Drizzle, not freezing, intermittent, moderate', category: 'DRIZZLE', description: 'Intermittent moderate drizzle', iconName: 'CloudDrizzle' },
  53: { code: 53, label: 'Drizzle, not freezing, continuous, moderate', category: 'DRIZZLE', description: 'Continuous moderate drizzle', iconName: 'CloudDrizzle' },
  54: { code: 54, label: 'Drizzle, not freezing, intermittent, heavy', category: 'DRIZZLE', description: 'Intermittent heavy drizzle', iconName: 'CloudDrizzle' },
  55: { code: 55, label: 'Drizzle, not freezing, continuous, heavy', category: 'DRIZZLE', description: 'Continuous heavy drizzle', iconName: 'CloudDrizzle' },
  56: { code: 56, label: 'Drizzle, freezing, slight', category: 'DRIZZLE', description: 'Slight freezing drizzle', iconName: 'CloudDrizzle' },
  57: { code: 57, label: 'Drizzle, freezing, moderate or heavy', category: 'DRIZZLE', description: 'Moderate/heavy freezing drizzle', iconName: 'CloudDrizzle' },
  58: { code: 58, label: 'Drizzle and rain, slight', category: 'RAIN', description: 'Slight drizzle and rain', iconName: 'CloudRain' },
  59: { code: 59, label: 'Drizzle and rain, moderate or heavy', category: 'RAIN', description: 'Moderate/heavy drizzle and rain', iconName: 'CloudRain' },
  60: { code: 60, label: 'Rain, not freezing, intermittent, slight', category: 'RAIN', description: 'Intermittent slight rain', iconName: 'CloudRain' },
  61: { code: 61, label: 'Rain, not freezing, continuous, slight', category: 'RAIN', description: 'Continuous slight rain', iconName: 'CloudRain' },
  62: { code: 62, label: 'Rain, not freezing, intermittent, moderate', category: 'RAIN', description: 'Intermittent moderate rain', iconName: 'CloudRain' },
  63: { code: 63, label: 'Rain, not freezing, continuous, moderate', category: 'RAIN', description: 'Continuous moderate rain', iconName: 'CloudRain' },
  64: { code: 64, label: 'Rain, not freezing, intermittent, heavy', category: 'RAIN', description: 'Intermittent heavy rain', iconName: 'CloudRain' },
  65: { code: 65, label: 'Rain, not freezing, continuous, heavy', category: 'RAIN', description: 'Continuous heavy rain', iconName: 'CloudRain' },
  66: { code: 66, label: 'Rain, freezing, slight', category: 'RAIN', description: 'Slight freezing rain', iconName: 'CloudRain' },
  67: { code: 67, label: 'Rain, freezing, moderate or heavy', category: 'RAIN', description: 'Moderate/heavy freezing rain', iconName: 'CloudRain' },
  68: { code: 68, label: 'Rain or drizzle and snow, slight', category: 'SNOW', description: 'Slight rain and snow', iconName: 'CloudSnow' },
  69: { code: 69, label: 'Rain or drizzle and snow, moderate or heavy', category: 'SNOW', description: 'Moderate/heavy rain and snow', iconName: 'CloudSnow' },
  70: { code: 70, label: 'Intermittent fall of snowflakes, slight', category: 'SNOW', description: 'Intermittent slight snow', iconName: 'Snowflake' },
  71: { code: 71, label: 'Continuous fall of snowflakes, slight', category: 'SNOW', description: 'Continuous slight snow', iconName: 'Snowflake' },
  72: { code: 72, label: 'Intermittent fall of snowflakes, moderate', category: 'SNOW', description: 'Intermittent moderate snow', iconName: 'Snowflake' },
  73: { code: 73, label: 'Continuous fall of snowflakes, moderate', category: 'SNOW', description: 'Continuous moderate snow', iconName: 'Snowflake' },
  74: { code: 74, label: 'Intermittent fall of snowflakes, heavy', category: 'SNOW', description: 'Intermittent heavy snow', iconName: 'Snowflake' },
  75: { code: 75, label: 'Continuous fall of snowflakes, heavy', category: 'SNOW', description: 'Continuous heavy snow', iconName: 'Snowflake' },
  76: { code: 76, label: 'Diamond dust (with or without fog)', category: 'SNOW', description: 'Diamond dust ice crystals', iconName: 'Snowflake' },
  77: { code: 77, label: 'Snow grains (with or without fog)', category: 'SNOW', description: 'Snow grains', iconName: 'Snowflake' },
  78: { code: 78, label: 'Isolated star-like snow crystals', category: 'SNOW', description: 'Snow crystals', iconName: 'Snowflake' },
  79: { code: 79, label: 'Ice pellets', category: 'HAIL', description: 'Ice pellets', iconName: 'CloudHail' },
  80: { code: 80, label: 'Rain shower(s), slight', category: 'RAIN', description: 'Slight rain shower', iconName: 'CloudRain' },
  81: { code: 81, label: 'Rain shower(s), moderate or heavy', category: 'RAIN', description: 'Moderate or heavy rain shower', iconName: 'CloudRain' },
  82: { code: 82, label: 'Rain shower(s), violent', category: 'RAIN', description: 'Violent torrential rain shower', iconName: 'CloudRain' },
  83: { code: 83, label: 'Shower(s) of rain and snow mixed, slight', category: 'SNOW', description: 'Slight rain/snow shower', iconName: 'CloudSnow' },
  84: { code: 84, label: 'Shower(s) of rain and snow mixed, moderate or heavy', category: 'SNOW', description: 'Moderate/heavy rain/snow shower', iconName: 'CloudSnow' },
  85: { code: 85, label: 'Snow shower(s), slight', category: 'SNOW', description: 'Slight snow shower', iconName: 'Snowflake' },
  86: { code: 86, label: 'Snow shower(s), moderate or heavy', category: 'SNOW', description: 'Moderate/heavy snow shower', iconName: 'Snowflake' },
  87: { code: 87, label: 'Shower(s) of snow pellets or small hail, slight', category: 'HAIL', description: 'Slight hail/pellet shower', iconName: 'CloudHail' },
  88: { code: 88, label: 'Shower(s) of snow pellets or small hail, moderate or heavy', category: 'HAIL', description: 'Moderate/heavy hail/pellet shower', iconName: 'CloudHail' },
  89: { code: 89, label: 'Shower(s) of hail, slight', category: 'HAIL', description: 'Slight hailstorm shower', iconName: 'CloudHail' },
  90: { code: 90, label: 'Shower(s) of hail, moderate or heavy', category: 'HAIL', description: 'Moderate/heavy hailstorm shower', iconName: 'CloudHail' },
  91: { code: 91, label: 'Slight rain, thunderstorm in past hour', category: 'THUNDERSTORM', description: 'Slight rain post-thunderstorm', iconName: 'Zap' },
  92: { code: 92, label: 'Moderate or heavy rain, thunderstorm in past hour', category: 'THUNDERSTORM', description: 'Moderate/heavy rain post-thunderstorm', iconName: 'Zap' },
  93: { code: 93, label: 'Slight snow or rain/snow mix, thunderstorm in past hour', category: 'THUNDERSTORM', description: 'Snow post-thunderstorm', iconName: 'Zap' },
  94: { code: 94, label: 'Mod/heavy snow or hail, thunderstorm in past hour', category: 'THUNDERSTORM', description: 'Hail post-thunderstorm', iconName: 'CloudHail' },
  95: { code: 95, label: 'Thunderstorm, slight or moderate, with rain/snow', category: 'THUNDERSTORM', description: 'Thunderstorm with precipitation', iconName: 'Zap' },
  96: { code: 96, label: 'Thunderstorm, slight or moderate, with hail', category: 'HAIL', description: 'Thunderstorm with hail', iconName: 'CloudHail' },
  97: { code: 97, label: 'Thunderstorm, heavy, with rain and/or snow', category: 'THUNDERSTORM', description: 'Heavy thunderstorm with rain', iconName: 'Zap' },
  98: { code: 98, label: 'Thunderstorm combined with duststorm or sandstorm', category: 'DUST', description: 'Thunderstorm with duststorm', iconName: 'Wind' },
  99: { code: 99, label: 'Thunderstorm, heavy, with hail', category: 'HAIL', description: 'Severe hailstorm & heavy lightning', iconName: 'CloudHail' },
};

export function getIMDWeatherCode(code: number | string | undefined | null): IMDWeatherCodeInfo {
  const numeric = typeof code === 'string' ? parseInt(code, 10) : (code ?? 0);
  if (isNaN(numeric) || !IMD_WEATHER_CODES[numeric]) {
    return {
      code: numeric || 0,
      label: 'Fair / Partly Cloudy',
      category: 'CLOUDY',
      description: 'Partly cloudy sky',
      iconName: 'CloudSun',
    };
  }
  return IMD_WEATHER_CODES[numeric];
}
